"""empty message

Revision ID: 1b3aa1e5f9be
Revises: 8cc1a7f5d8b
Create Date: 2015-09-12 17:00:30.709519

"""

# revision identifiers, used by Alembic.
revision = '1b3aa1e5f9be'
down_revision = '8cc1a7f5d8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celery_tasksetmeta')
    op.drop_table('sqlite_sequence')
    op.drop_table('celery_taskmeta')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_taskmeta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', sa.DATETIME(), nullable=True),
    sa.Column('traceback', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('celery_tasksetmeta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('taskset_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taskset_id')
    )
    ### end Alembic commands ###
