"""empty message

Revision ID: 1c039b5071bf
Revises: 1bbb57d4b290
Create Date: 2015-09-19 17:59:15.969588

"""

# revision identifiers, used by Alembic.
revision = '1c039b5071bf'
down_revision = '1bbb57d4b290'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap_task', sa.Column('test', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nmap_task', 'test')
    ### end Alembic commands ###
