"""empty message

Revision ID: 2316d9487dbe
Revises: 2971e17ada32
Create Date: 2015-10-01 20:31:57.995298

"""

# revision identifiers, used by Alembic.
revision = '2316d9487dbe'
down_revision = '2971e17ada32'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nmap_report_meta', 'task_task_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap_report_meta', sa.Column('task_task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
