"""empty message

Revision ID: 252e1ff4180f
Revises: ed0b0409e5
Create Date: 2015-09-21 21:19:01.550806

"""

# revision identifiers, used by Alembic.
revision = '252e1ff4180f'
down_revision = 'ed0b0409e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'address_detail_ibfk_1', 'address_detail', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'address_detail_ibfk_1', 'address_detail', 'address', ['address_id'], ['id'])
    ### end Alembic commands ###
