"""empty message

Revision ID: 2971e17ada32
Revises: 43b1c9fba74c
Create Date: 2015-10-01 20:21:08.877997

"""

# revision identifiers, used by Alembic.
revision = '2971e17ada32'
down_revision = '43b1c9fba74c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nmap_report_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_task_id', sa.Integer(), nullable=True),
    sa.Column('task_comment', sa.String(length=128), nullable=True),
    sa.Column('task_created', sa.DateTime(), nullable=True),
    sa.Column('task_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nmap_report_meta')
    ### end Alembic commands ###
