"""empty message

Revision ID: 2be8e4a8df84
Revises: 34412629160
Create Date: 2015-10-03 20:04:00.423641

"""

# revision identifiers, used by Alembic.
revision = '2be8e4a8df84'
down_revision = '34412629160'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap_task', sa.Column('completed', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nmap_task', 'completed')
    ### end Alembic commands ###
