"""empty message

Revision ID: 2e06c0b8d05c
Revises: 390cd291e351
Create Date: 2015-10-03 18:10:42.345906

"""

# revision identifiers, used by Alembic.
revision = '2e06c0b8d05c'
down_revision = '390cd291e351'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap_report_meta', sa.Column('report_stored', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nmap_report_meta', 'report_stored')
    ### end Alembic commands ###
