"""empty message

Revision ID: 2e34cc01b0cb
Revises: 1e38646e0417
Create Date: 2015-10-05 22:08:24.171408

"""

# revision identifiers, used by Alembic.
revision = '2e34cc01b0cb'
down_revision = '1e38646e0417'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap_task', sa.Column('completed_status', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nmap_task', 'completed_status')
    ### end Alembic commands ###
