"""empty message

Revision ID: 2e75df2d6adc
Revises: 2e06c0b8d05c
Create Date: 2015-10-03 18:11:22.025330

"""

# revision identifiers, used by Alembic.
revision = '2e75df2d6adc'
down_revision = '2e06c0b8d05c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nmap_report_meta', 'report_finished')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap_report_meta', sa.Column('report_finished', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
