"""empty message

Revision ID: 339b1d637991
Revises: 252e1ff4180f
Create Date: 2015-09-23 20:58:54.221557

"""

# revision identifiers, used by Alembic.
revision = '339b1d637991'
down_revision = '252e1ff4180f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.add_column('address_detail', sa.Column('ip_address', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
    op.drop_column('address_detail', 'address_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_detail', sa.Column('address_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('address_detail', 'ip_address')
    op.create_table('address',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(collation=u'utf8_bin', length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
