"""empty message

Revision ID: 34412629160
Revises: 2e75df2d6adc
Create Date: 2015-10-03 19:03:09.209929

"""

# revision identifiers, used by Alembic.
revision = '34412629160'
down_revision = '2e75df2d6adc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap_report_meta', sa.Column('report_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nmap_report_meta', 'report_id')
    ### end Alembic commands ###
