"""empty message

Revision ID: 3bc6c5402bbb
Revises: 339b1d637991
Create Date: 2015-09-23 21:03:07.570959

"""

# revision identifiers, used by Alembic.
revision = '3bc6c5402bbb'
down_revision = '339b1d637991'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_detail', sa.Column('ip_address', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_detail', 'ip_address')
    ### end Alembic commands ###
