"""empty message

Revision ID: 3c6576a5f7e3
Revises: 2e34cc01b0cb
Create Date: 2015-10-07 17:53:51.269757

"""

# revision identifiers, used by Alembic.
revision = '3c6576a5f7e3'
down_revision = '2e34cc01b0cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('sso_enabled', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sso_enabled')
    op.drop_column('user', 'last_update')
    ### end Alembic commands ###
