"""empty message

Revision ID: 40986f177011
Revises: 1c039b5071bf
Create Date: 2015-09-21 19:42:24.067867

"""

# revision identifiers, used by Alembic.
revision = '40986f177011'
down_revision = '1c039b5071bf'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    ### end Alembic commands ###
