"""empty message

Revision ID: 43b1c9fba74c
Revises: 3bc6c5402bbb
Create Date: 2015-09-23 21:04:24.827616

"""

# revision identifiers, used by Alembic.
revision = '43b1c9fba74c'
down_revision = '3bc6c5402bbb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_detail', 'address_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_detail', sa.Column('address_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
