"""empty message

Revision ID: 49486ecb5965
Revises: 1b3aa1e5f9be
Create Date: 2015-09-12 17:02:55.100804

"""

# revision identifiers, used by Alembic.
revision = '49486ecb5965'
down_revision = '1b3aa1e5f9be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nmap_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sqlite_sequence')
    op.drop_table('celery_taskmeta')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_taskmeta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', sa.DATETIME(), nullable=True),
    sa.Column('traceback', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('nmap_task')
    ### end Alembic commands ###
