"""empty message

Revision ID: 4a9a1dc82e00
Revises: 52e982c8dab6
Create Date: 2015-10-04 02:54:59.118313

"""

# revision identifiers, used by Alembic.
revision = '4a9a1dc82e00'
down_revision = '52e982c8dab6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('inactive', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'inactive')
    op.drop_column('user', 'created')
    ### end Alembic commands ###
