"""empty message

Revision ID: 52e982c8dab6
Revises: 2be8e4a8df84
Create Date: 2015-10-03 23:10:01.426454

"""

# revision identifiers, used by Alembic.
revision = '52e982c8dab6'
down_revision = '2be8e4a8df84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('comment', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'comment')
    ### end Alembic commands ###
