"""empty message

Revision ID: 57befcbd2be6
Revises: 2316d9487dbe
Create Date: 2015-10-01 20:32:11.245440

"""

# revision identifiers, used by Alembic.
revision = '57befcbd2be6'
down_revision = '2316d9487dbe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nmap_report_meta', sa.Column('task_task_id', sa.String(length=36), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nmap_report_meta', 'task_task_id')
    ### end Alembic commands ###
