"""empty message

Revision ID: 8cc1a7f5d8b
Revises: 8017a208210
Create Date: 2015-09-12 14:13:45.263269

"""

# revision identifiers, used by Alembic.
revision = '8cc1a7f5d8b'
down_revision = '8017a208210'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('user', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('user', 'user_id')
    ### end Alembic commands ###
