"""empty message

Revision ID: bda50e7b323
Revises: 25121b58df52
Create Date: 2015-10-09 20:26:17.455840

"""

# revision identifiers, used by Alembic.
revision = 'bda50e7b323'
down_revision = '25121b58df52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_group', ['user_group_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_group_id')
    ### end Alembic commands ###
