"""empty message

Revision ID: ed0b0409e5
Revises: 4dd09c440a0c
Create Date: 2015-09-21 20:53:53.657134

"""

# revision identifiers, used by Alembic.
revision = 'ed0b0409e5'
down_revision = '4dd09c440a0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_detail', sa.Column('report_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_detail', 'report_id')
    ### end Alembic commands ###
