# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nmap', '0006_auto_20151024_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name=b'date update')),
                ('address', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=0)),
                ('protocol', models.CharField(choices=[(b'TCP', b'TCP'), (b'UDP', b'UDP'), (b'OTHER', b'Other')], max_length=20)),
                ('nmap_report_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmap.NmapReportMeta')),
            ],
        ),
    ]
