# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nmap', '0007_networkservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkservice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
