# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmap', '0008_auto_20160322_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkservice',
            name='banner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='networkservice',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='networkservice',
            name='service',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='networkservice',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
