# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmap', '0009_auto_20160322_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkservice',
            name='protocol',
            field=models.CharField(choices=[(b'tcp', b'TCP'), (b'udp', b'UDP'), (b'other', b'Other')], max_length=20),
        ),
    ]
