"""empty message

Revision ID: 3c80479b033
Revises: None
Create Date: 2015-10-09 19:49:38.535485

"""

# revision identifiers, used by Alembic.
revision = '3c80479b033'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('inactive', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('sso_enabled', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_addressdetail',
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('address_detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_detail_id'], ['address_detail.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], )
    )
    op.create_table('nmap_report_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_task_id', sa.String(length=36), nullable=True),
    sa.Column('task_comment', sa.String(length=128), nullable=True),
    sa.Column('task_created', sa.DateTime(), nullable=True),
    sa.Column('report_stored', sa.DateTime(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('task_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nmap_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.SmallInteger(), nullable=True),
    sa.Column('completed_status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nmap_task')
    op.drop_table('nmap_report_meta')
    op.drop_table('contact_addressdetail')
    op.drop_table('user_group')
    op.drop_table('user')
    op.drop_table('contact')
    op.drop_table('address_detail')
    ### end Alembic commands ###
